//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobcastInsightRequest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.JobCategories = new HashSet<JobCategory>();
        }
    
        public int Id { get; set; }
        public string ReferenceId { get; set; }
        public Nullable<System.DateTime> PostedAt { get; set; }
        public int Source_Id { get; set; }
        public Nullable<double> Rate_From { get; set; }
        public Nullable<double> Rate_To { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public int Processor_Id { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public int CreatedBy_Id { get; set; }
        public int Title_Id { get; set; }
        public int UpdatedBy_Id { get; set; }
        public System.DateTime OpenedAt { get; set; }
        public System.DateTime OpenedTill { get; set; }
        public string Rate_Currency { get; set; }
        public int Rate_Type { get; set; }
        public string Rate_Description { get; set; }
        public Nullable<int> ManagementLevel { get; set; }
        public Nullable<int> MinExperience { get; set; }
        public Nullable<int> MaxExperience { get; set; }
    
        public virtual JobSource JobSource { get; set; }
        public virtual JobTitle JobTitle { get; set; }
        public virtual Processor Processor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobCategory> JobCategories { get; set; }
    }
}
