//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobcastInsightRequest
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobCategory
    {
        public int JobId { get; set; }
        public int SubCategoryId { get; set; }
    
        public virtual Job Job { get; set; }
    }
}
